import sympy as sp
x,y,z=sp.symbols('x,y,z')
f=input("enter the function :")
print("the first derivstive wrt x: ")
sp.pprint(sp.diff(f,x))
print("the first derivstive wrt y: ")
sp.pprint(sp.diff(f,y))
print("the first derivstive wrt z: ")
sp.pprint(sp.diff(f,z))
print("the second derivstive wrt x: ")
sp.pprint(sp.diff(f,x,x))
print("the first derivstive wrt y: ")
sp.pprint(sp.diff(f,y,y))
print("the first derivstive wrt z: ")
sp.pprint(sp.diff(f,z,z))
print("the first derivstive wrt x,y:")
sp.pprint(sp.diff(f,x,y))
print("the first derivstive wrt y,z: ")
sp.pprint(sp.diff(f,y,z))
print("the first derivstive wrt x,y,z: ")
sp.pprint(sp.diff(f,x,y,z))
